### ISSUE TITLE
Abbreviate too much

### ISSUE THREAD

**Issue by snowthesprite** [walliuswilliam/graph#1]
Heyo William. Its as simple as it says, you abbreviate too much. If we're going by how understandable your assert is to someone who's not you, I didn't know what NBF was until I looked at your code. Just give a little more detail like "finished Node breadth 1st" or something like that so that when someone else is looking at your code or your coming back after a while, you already know what's done.

**Comment by walliuswilliam** [comment]
yeah I didnt realize that the pushes to github dont stack (so if i spell out the entire thing in one push, then abbreviate in another) its not completely obvious. thanks for the heads up though
